# Generated by Django 4.1.7 on 2023-03-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('domain', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('integer', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
